[package]
name = "dat-edit"
version = "0.2.0"
edition = "2024"
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["melee", "gamecube", "hsd", "dat", "modding"]
categories = ["game-development"]
description = "In-place edits to HSD DAT archives"

[dependencies]
dat-parser = { version = "0.2.0", path = "../dat-parser" }
gx-texture = { version = "0.2.0", path = "../gx-texture" }
thiserror = "2"

[lints]
workspace = true
